version: 2.1

jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate

  quality:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py check
            flake8

  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest

  image_docker:
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: olrio/orange_lettings2
          docker:
            - image: python:latest
          auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" - password-stdin
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME:latest

workflows:
  build-workflow:
    jobs:
      - build
      - quality
      - test
      - image_docker
