version: 2.1

jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate

  quality:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py check
            flake8

  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest

  image_docker:
    steps:
      - run:
          command: |
            docker login
            docker build -t olrio_orange_lettings .
            docker tag olrio_orange_lettings:latest olrio/orange_lettings:latest
            docker push olrio/orange_lettings:latest

workflows:
  build-workflow:
    jobs:
      - build
      - quality
      - test
      - image_docker
