version: 2.1

jobs:
  build:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py makemigrations
            python manage.py migrate

  quality:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py check
            flake8

  test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command:  |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest
  
  deploy:
    docker:
      - image: cimg/python:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker build -t $HUB_NAME:latest
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker tag $HUB_NAME $DOCKER_LOGIN/$HUB_NAME
            docker push $DOCKER_LOGIN/$HUB_NAME
    


workflows:
  build-workflow:
    jobs:
      - build
      - quality
      - test
      - deploy
